version: "3"

services:

  app:
    build: .
    env_file:
      - .env
    volumes:
      - ./:/src
    command: ./codeship/build.sh

  gosec:
    image: securego/gosec:latest
    volumes:
      - ./:/src
    # Remember to make the exclude value match the corresponding line in codeship-steps.yml
    command: ["-exclude=G104", "-quiet", "/src/..."]

