service: wecarry-lambdas

frameworkVersion: ^3.2.0

provider:
  name: aws
  runtime: go1.x
  timeout: 240
  versionFunctions: false
  memorySize: 128
  logRetentionInDays: 14
  stage: stg

  # you can define service wide environment variables here
  environment:
    SERVICE_INTEGRATION_URL: ${env:SERVICE_INTEGRATION_URL}
    SERVICE_INTEGRATION_TOKEN: ${env:SERVICE_INTEGRATION_TOKEN}

package:
  patterns:
  - '!./**'
  - './bin/**'

functions:
  maintenance:
    handler: bin/maintenance
    events:
    # cron(Minutes Hours Day-of-month Month Day-of-week Year)
    # Either `day-of-month` or `day-of-week` must be a question mark (?)
    - schedule: cron(0 4 ? * SUN *)

  outdatedRequests:
    handler: bin/outdatedrequests
    events:
      # cron(Minutes Hours Day-of-month Month Day-of-week Year)
      # Either `day-of-month` or `day-of-week` must be a question mark (?)
      - schedule: cron(0 4 ? * FRI *)
